"""
Project Euler Problem #2
=========================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

a, b, ans = 1, 2, 2
while True:
    nextFib = a + b
    if nextFib > 4000000:
        break
    if nextFib % 2 == 0:
        ans += nextFib
    a, b = b, nextFib

print ans
