"""
Project Euler Problem #44
==========================

Pentagonal numbers are generated by the formula, P[n]=n(3n-1)/2. The first
ten pentagonal numbers are:

               1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
and difference is pentagonal and D = |P[k] - P[j]| is minimised; what is
the value of D?
"""


def p(n):
    return n*(3*n-1)/2


def is_p(x):
    a = (24 * x + 1) ** .5
    return int(a) == a and (a + 1) % 6 == 0


for i in xrange(2, 10000):
    pi = p(i)
    for j in xrange(1, i):
        pj = p(j)
        if is_p(pi-pj) and is_p(pi+pj):
            print pi-pj
            exit()







